#!/bin/bash
echo "BOOLEANS"
for file in python-reference/bool/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

echo "BUILTINS"
for file in python-reference/builtin/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

echo "DICT"
echo "bool"
racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < python-reference/dict/dict-bool.py
echo "contains"
racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < python-reference/dict/dict-contains.py
echo "get"
racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < python-reference/dict/dict-get.py
echo "update"
racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < python-reference/dict/dict-clear.py


echo "EXCEPTIONS"
for file in python-reference/exceptions/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

echo "LISTS"
for file in python-reference/lists/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

echo "SCOPE"
for file in python-reference/scope/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

echo "TUPLE"
for file in python-reference/tuple/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

echo "TYPES"
for file in python-reference/types/*.py
do
	echo "${file}"
	racket ~/python/python-main.rkt --python-path /course/cs173/python/Python-3.2.3/python --interp < "${file}"
done

