print("HI")
___assertIs(isinstance(True, bool), True)
print("HI")
___assertIs(isinstance(False, bool), True)
print("HI")
___assertIs(isinstance(True, int), True)
print("HI")
___assertIs(isinstance(False, int), True)
print("HI")
___assertIs(isinstance(1, bool), False)
print("HI")
___assertIs(isinstance(0, bool), False)
